//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirPlane
    {
        public AirPlane()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int AirplaneID { get; set; }
        public string AirplaneCode { get; set; }
        public Nullable<int> Seats_FirstClass { get; set; }
        public Nullable<int> Seats_Economy { get; set; }
        public Nullable<double> Price_FirstClass { get; set; }
        public Nullable<double> Price_Economy { get; set; }
    
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
