//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Seats = new HashSet<Seat>();
        }
    
        public int ScheduleID { get; set; }
        public Nullable<int> AirplaneID { get; set; }
        public string Airport_Departure { get; set; }
        public string Airport_Arrival { get; set; }
        public Nullable<System.DateTime> Time_Departure { get; set; }
        public Nullable<System.DateTime> Time_Arrival { get; set; }
    
        public virtual AirPlane AirPlane { get; set; }
        public virtual ICollection<Seat> Seats { get; set; }
    }
}
