//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int SeatID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public string SeatType { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual User User { get; set; }
    }
}
